### ISSUE TITLE
loss of main menu when TOC is used

### ISSUE THREAD

**Issue by whatcoloris** [emergencyindex/emergencyindex.com#35]
when i first started using the site this freaked me out,
and now i've had some other friends start mentioning it.

when the TOC gets used (Volume and Index views), the main menu disappears. you're like "WTF WHERE AM I" - once you click on the "Emergency Index" title and you get back home you're like "Oh I get it" - but maybe there's a way to make things a little clearer?

possibly something that hangs below the "Emergency Index" title or a change in the color of "Emergency Index" title that relates to the main menu?

will do some thinking on this...

**Comment by edwardsharp** [comment]
well, not so-much disappears as it's at the top and long TOCs can make it hard to get back to, yeah?

**Comment by whatcoloris** [comment]
right exactly!
