### ISSUE TITLE
social nav floating on iPhone (small-and-down) media

### ISSUE THREAD

**Issue by whatcoloris** [emergencyindex/emergencyindex.com#9]
if we remove position: unset from the media query in nav.scss then the social-nav doesn't free float anymore which i think is kind of nice, is that there because of the "dance" for the table of contents (for contributors, terms, volume pages, etc)?

if that's the case i propose we just yank it whenever the sidebar expands into a toc, will be working on js to make the blob do that today!

**Comment by edwardsharp** [comment]
i think that might be there because of the annoying thing on iPhone where
the bottom 64px of the screen is sometimes the safari nav and sometimes
not.

look forward to seeing what you come up with

**Comment by whatcoloris** [comment]
my proposed fix would be get rid of it when the table of contents are down and when there's safari detected bump it up???? would that work? i never use safari i'm realizing...

**Comment by whatcoloris** [comment]
this is also fine honestly. we've got bigger fish to fry!
